# Generated by Django 3.2.21 on 2023-10-09 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventario',
            old_name='Nombre',
            new_name='NombreItem',
        ),
        migrations.RemoveField(
            model_name='inventario',
            name='id',
        ),
        migrations.AlterField(
            model_name='inventario',
            name='Id_Inventario',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
