# Generated by Django 4.1.4 on 2023-10-04 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='interests',
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='', upload_to='users/'),
        ),
        migrations.DeleteModel(
            name='Interest',
        ),
    ]
