# Generated by Django 4.1.4 on 2023-10-12 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_profile_address_profile_age_profile_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='puestoTrabajo',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
