# Generated by Django 4.1.4 on 2023-10-13 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_usermodification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserModification',
        ),
    ]
