# Generated by Django 4.2.3 on 2023-09-27 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='unidades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Placa_Vehiculo', models.CharField(default=0, max_length=100)),
                ('Tipo_de_Vehiculo', models.CharField(default=0, max_length=100)),
                ('Capacidad_Carga', models.CharField(default=0, max_length=100)),
                ('Estado_unidad', models.CharField(choices=[('1', 'Disponible'), ('2', 'En Mantenimiento'), ('3', 'En Tránsito')], default=0, max_length=30)),
                ('Observaciones', models.CharField(default=0, max_length=100)),
            ],
        ),
    ]
