# Generated by Django 3.2.21 on 2023-10-09 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unidades', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unidades',
            name='Capacidad_Carga',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='unidades',
            name='Estado_unidad',
            field=models.CharField(choices=[('1', 'Disponible'), ('2', 'En Mantenimiento'), ('3', 'En Tránsito')], max_length=30),
        ),
        migrations.AlterField(
            model_name='unidades',
            name='Observaciones',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='unidades',
            name='Placa_Vehiculo',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='unidades',
            name='Tipo_de_Vehiculo',
            field=models.CharField(max_length=100),
        ),
    ]
