# Generated by Django 3.2.21 on 2023-10-09 21:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unidades', '0002_auto_20231009_1329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unidades',
            name='Capacidad_Carga',
            field=models.IntegerField(max_length=100),
        ),
        migrations.AlterField(
            model_name='unidades',
            name='Estado_unidad',
            field=models.CharField(choices=[('Disponible', 'Disponible'), ('En Mantenimiento', 'En Mantenimiento'), ('En Tránsito', 'En Tránsito')], max_length=30),
        ),
        migrations.AlterField(
            model_name='unidades',
            name='Placa_Vehiculo',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator('^[A-Za-z0-9]{3}\\d{3}$', 'Ingrese una placa válida.')]),
        ),
    ]
