# Generated by Django 3.2.21 on 2023-10-09 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unidades', '0003_auto_20231009_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unidades',
            name='Capacidad_Carga',
            field=models.IntegerField(),
        ),
    ]
