# Generated by Django 4.2.3 on 2023-12-10 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unidades', '0004_alter_unidades_capacidad_carga'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unidades',
            name='Placa_Vehiculo',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='unidades',
            name='Tipo_de_Vehiculo',
            field=models.CharField(choices=[('Camión articulado', 'Camión articulado'), ('Camión rígido', 'Camión rígido'), ('Camión cerrado', 'Camión cerrado'), ('Camión contenedor', 'Camión contenedor')], max_length=100),
        ),
    ]
