# Generated by Django 4.2 on 2023-09-10 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empleados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=40)),
                ('Apellido', models.CharField(max_length=40)),
                ('DNI', models.IntegerField()),
                ('Telefono', models.IntegerField()),
                ('Correo', models.CharField(max_length=40)),
                ('Estado_Licencia', models.CharField(choices=[('1', 'Valido'), ('2', 'Restringido')], max_length=20)),
                ('Observaciones', models.CharField(max_length=100)),
                ('Rendimiento', models.CharField(max_length=50)),
            ],
        ),
    ]
