# Generated by Django 3.2.21 on 2023-10-09 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleados',
            name='Licencia',
            field=models.CharField(choices=[('1', 'A-I'), ('2', 'A-IIa'), ('3', 'A-IIb'), ('4', 'A-IIIa'), ('5', 'A-IIIb'), ('6', 'A-IIIc'), ('7', 'B-I'), ('8', 'B-IIa'), ('9', 'B-IIb'), ('10', 'B-IIc')], default='Valor Predeterminado', max_length=50),
        ),
        migrations.AlterField(
            model_name='empleados',
            name='Estado_Licencia',
            field=models.CharField(choices=[('1', 'Vigente'), ('2', 'Suspendida'), ('3', 'Vencida'), ('4', 'Invalida')], max_length=20),
        ),
    ]
