# Generated by Django 3.2.21 on 2023-10-10 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0002_auto_20231009_1329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleados',
            name='Estado_Licencia',
            field=models.CharField(choices=[('1', 'Vigente'), ('2', 'Suspendida'), ('3', 'Vencida'), ('4', 'Invalida')], default='Valor Predeterminado', max_length=20),
        ),
    ]
