# Generated by Django 4.2.3 on 2023-11-29 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0003_alter_empleados_estado_licencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleados',
            name='Rendimiento',
            field=models.CharField(choices=[('1', 'Excelente'), ('2', 'Bueno'), ('3', 'Regular'), ('4', 'Necesita Mejorar'), ('5', 'Deficiente.')], default='Valor Predeterminado', max_length=50),
        ),
    ]
