# Generated by Django 4.2 on 2023-09-10 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='clientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tipo_Ruc', models.CharField(choices=[('1', 'RUC10'), ('2', 'RUC20')], default=0, max_length=20)),
                ('Ruc_Clientes', models.IntegerField(default=0)),
                ('Cliente_Nombre', models.CharField(default=0, max_length=100)),
                ('Cliente_Apellido', models.CharField(default=0, max_length=100)),
                ('Cliente_telefono', models.DecimalField(decimal_places=0, default=0, max_digits=9)),
                ('Cliente_email', models.EmailField(default=0, max_length=254)),
                ('Cliente_direccion', models.CharField(default=0, max_length=100)),
                ('Valoracion', models.IntegerField(default=0)),
                ('Tipo_Mercaderia', models.CharField(default=0, max_length=12)),
            ],
        ),
    ]
