# Generated by Django 3.2.21 on 2023-10-09 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='Cliente_Apellido',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='Cliente_Nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='Cliente_direccion',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='Cliente_email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='Cliente_telefono',
            field=models.DecimalField(decimal_places=0, max_digits=9),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='Ruc_Clientes',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='Tipo_Mercaderia',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='Tipo_Ruc',
            field=models.CharField(choices=[('1', 'RUC10'), ('2', 'RUC20')], max_length=20),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='Valoracion',
            field=models.IntegerField(),
        ),
    ]
