# Generated by Django 3.2.21 on 2023-10-09 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_auto_20231009_1329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='Ruc_Clientes',
            field=models.IntegerField(unique=True),
        ),
    ]
