# Generated by Django 3.2.21 on 2023-10-09 21:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_alter_clientes_ruc_clientes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='Cliente_Apellido',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator('^[a-zA-ZáéíóúÁÉÍÓÚñÑ\\s]+$', 'Ingrese solo letras.')]),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='Cliente_Nombre',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator('^[a-zA-ZáéíóúÁÉÍÓÚñÑ\\s]+$', 'Ingrese solo letras.')]),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='Ruc_Clientes',
            field=models.CharField(max_length=11, unique=True, validators=[django.core.validators.RegexValidator('^\\d{11}$', 'El RUC debe contener 11 dígitos.')]),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='Tipo_Ruc',
            field=models.CharField(choices=[('RUC10', 'RUC10'), ('RUC20', 'RUC20')], max_length=20),
        ),
    ]
