# Generated by Django 4.2.3 on 2023-11-29 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0004_auto_20231009_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='Cliente_Apellido',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='Cliente_Nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='Cliente_telefono',
            field=models.CharField(max_length=9),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='Ruc_Clientes',
            field=models.CharField(max_length=11, unique=True),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='Tipo_Mercaderia',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='Tipo_Ruc',
            field=models.CharField(choices=[('RUC10', 'RUC10'), ('RUC20', 'RUC20')], max_length=5),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='Valoracion',
            field=models.CharField(choices=[('Malo', 'Malo'), ('Bueno', 'Bueno'), ('Excelente', 'Excelente')], default='Valor Predeterminado', max_length=20),
        ),
    ]
