# Generated by Django 4.2.3 on 2023-07-23 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='Numero_de_factura',
            field=models.IntegerField(),
        ),
    ]
