# Generated by Django 4.2.3 on 2023-07-23 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturas', '0002_alter_factura_numero_de_factura'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='Documento_factura',
            field=models.FileField(upload_to='archivos/'),
        ),
    ]
