# Generated by Django 3.2.21 on 2023-10-09 20:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_alter_clientes_ruc_clientes'),
        ('facturas', '0003_alter_factura_documento_factura'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='factura',
            name='Numero_de_factura',
        ),
        migrations.AlterField(
            model_name='factura',
            name='Documento_factura',
            field=models.FileField(upload_to='archivos/', verbose_name='Documento de factura'),
        ),
        migrations.AlterField(
            model_name='factura',
            name='Id_cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.clientes', to_field='Ruc_Clientes', verbose_name='RUC del cliente'),
        ),
        migrations.AlterField(
            model_name='factura',
            name='Pago_de_detraccion',
            field=models.BooleanField(verbose_name='Pago de detraccion'),
        ),
    ]
