# Generated by Django 4.2.3 on 2023-11-29 06:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0005_alter_clientes_cliente_apellido_and_more'),
        ('facturas', '0004_auto_20231009_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='Fecha_Emision',
            field=models.DateField(verbose_name='Fecha de ingreso'),
        ),
        migrations.AlterField(
            model_name='factura',
            name='Id_cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.clientes', to_field='Ruc_Clientes', verbose_name='Nombre del cliente'),
        ),
    ]
