# Generated by Django 4.2 on 2023-12-16 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orden_de_trabajo', '0002_remove_orden_trabajo_ruc_cliente_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orden_trabajo',
            name='Tipo_orden_de_trabajo',
            field=models.CharField(choices=[('No tercerizada', 'No tercerizada'), ('Tercerizada', 'Tercerizada')], max_length=20),
        ),
    ]
