# Generated by Django 4.2 on 2023-12-16 01:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orden_de_trabajo', '0003_alter_orden_trabajo_tipo_orden_de_trabajo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orden_trabajo',
            name='Tipo',
        ),
    ]
