# Generated by Django 4.2 on 2023-09-10 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=100)),
                ('Direccion', models.CharField(max_length=200)),
                ('Correo', models.EmailField(max_length=254)),
                ('Telefono', models.CharField(max_length=20)),
                ('Valoracion', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')])),
                ('TipoProducto', models.CharField(max_length=100)),
                ('DocumentacionLegal', models.FileField(upload_to='documentacion_legal/')),
            ],
        ),
    ]
