# Generated by Django 4.2.3 on 2023-11-29 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedor',
            name='Apellido',
            field=models.CharField(default='doce', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='Telefono',
            field=models.CharField(max_length=9),
        ),
    ]
