# Generated by Django 4.2 on 2023-12-16 00:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0002_proveedor_apellido_alter_proveedor_telefono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedor',
            name='Telefono',
            field=models.IntegerField(help_text='El numero de telefono debe tener 9 digitos', validators=[django.core.validators.MaxValueValidator(999999999, message='Este campo debe tener exactamente 9 dígitos.'), django.core.validators.MinValueValidator(900000000, message='Este campo debe tener exactamente 9 dígitos.')]),
        ),
    ]
