# Generated by Django 4.2 on 2023-09-10 23:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('facturas', '0001_initial'),
        ('inventario', '0001_initial'),
        ('orden_de_trabajo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='gastos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Codigo_de_boleta', models.IntegerField()),
                ('Tipo_de_gasto', models.CharField(max_length=100)),
                ('Area_de_gasto', models.CharField(max_length=100)),
                ('Descripcion', models.TextField(max_length=500)),
                ('Monto_gastado', models.DecimalField(decimal_places=2, max_digits=7)),
                ('Fecha_boleta', models.DateField()),
                ('Documento_boleta', models.FileField(upload_to='DocGastos/')),
                ('Factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facturas.factura')),
                ('Inventario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.inventario')),
                ('Orden_de_trabajo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orden_de_trabajo.orden_trabajo')),
            ],
        ),
    ]
