# Generated by Django 3.2.21 on 2023-10-10 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gastos', '0002_auto_20231009_1758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gastos',
            name='Area_de_gasto',
            field=models.CharField(choices=[('1', 'Gasto Administrativo'), ('2', 'Gasto en Combustible'), ('3', 'Gasto en Mantenimiento'), ('4', 'Gasto en Repuestos'), ('5', 'Gasto en Salarios/Sueldos'), ('6', 'Gasto en Estibaje'), ('7', 'Gastos en impuestos tributarios')], default='Valor Predeterminado', max_length=100),
        ),
        migrations.AlterField(
            model_name='gastos',
            name='Tipo_de_gasto',
            field=models.CharField(choices=[('1', 'Gasto Fijo'), ('2', 'Gasto variable')], default='Valor Predeterminado', max_length=100),
        ),
    ]
